#!/bin/sh
. $IPKG_INSTROOT/lib/functions.sh

start_instance() {
	config_get Refreshinterval "$1" 'Refreshinterval' '3s'
	config_get Errorcount "$1" 'Errorcount' '3'
	config_get Actionmethod "$1" 'Actionmethod' '0'
	config_get Actiontime "$1" 'Actiontime' '60' ; }
	config_load 'banlogon'
	config_foreach start_instance 'basic' ; timeout='0'
	[ "$Actionmethod" -gt 0 ] && timeout="$Actiontime"

carried() {
	cat /etc/banlogon/whitelist.list|sed '/#/d'|grep -wq $2||{ [ -n "${2/*:*}" ]&&\
	ipset add ${1}4 $2 timeout $timeout 2>/dev/null||ipset add ${1}6 $2 timeout $timeout 2>/dev/null ; }
}

main() {
	while : ; do unset u ; unset d ;
	[ "$1" == "uhttpd" -o "$2" == "uhttpd" ] && {
	u=$(logread -e uhttpd|grep 'failed login on'|\
	awk '{print $16}'|uniq -c|awk '{if($1>='"$Errorcount"') print $2}')
	[ -n "$u" ] && for u in $u ; do carried uhttpd $u ; done ; }

	[ "$1" == "dropbear" -o "$2" == "dropbear" ] && {
	d=$(logread -e dropbear|grep 'Bad password attempt'|awk '{print $14}'|\
	sed 's/\(.*\):/\1 /'|awk '{print $1}'|uniq -c|awk '{if($1>='"$Errorcount"') print $2}')
	[ -n "$d" ] && for d in $d ; do carried dropbear $d ; done ; }

	sleep $Refreshinterval ; done ; }

usage() {
	cat <<EOF
Usage: $0 [options] <command> [arguments]
Commands:

	-a	监视	uhttpd or dropbear
	-h	帮助	显示帮助信息并退出
	-v	版本	显示版本信息并退出

Options:

EOF
	exit ${1:-1}
}

COMMAND="$1"; shift
case "$COMMAND" in
	-h) usage 0;;
	-a) main $@;;
	-v) echo 'v1.0 版权归属：一切源于网络搜索与分享';;
	*) usage 0;;
esac
