#!/bin/sh

start() {
	
	if [ ! -d /usr/share/JD_Script ]
		echo "JD_Script已存在"
	else
		npm install -g crypto-js got http-server tough-cookie download request tunnel && Detect
		git clone https://github.com/ITdesk01/JD_Script.git /usr/share/JD_Script && Detect
		chmod +x /usr/share/JD_Script/jd.sh 
		sh /usr/share/JD_Script/jd.sh system_variable
	fi

	if [ ! -d /usr/share/Checkjs ]
		echo "Checkjs已存在"
	else
		git clone https://github.com/ITdesk01/Checkjs.git /usr/share/Checkjs && Detect
		chmod +x /usr/share/Checkjs/checkjs.sh
		sh /usr/share/Checkjs/checkjs.sh system_variable 
	fi
	
	if [ ! -d /usr/share/AUCloudflareIP ]
		echo "AUCloudflareIP已存在"
	else
		git clone https://github.com/ITdesk01/AUCloudflareIP.git /usr/share/AUCloudflareIP && Detect
		chmod +x /usr/share/AUCloudflareIP/AUCloudflareIP.sh
		sh /usr/share/AUCloudflareIP/AUCloudflareIP.sh system_variable
	fi
	exit 0
}


Detect() {
	if [ $? -eq 0 ]; then
		echo  ""
	else
		echo "代码运行失败重新执行"
		start
	fi
}

start
